export const SKILLS = [
  'React',
  'Angular',
  'Vue.js',
  'Node.js',
  'Laravel',
  'Django',
  'Spring Boot',
  'Ruby on Rails',
  'Flask',
  'Express.js',
  'TensorFlow',
  'Keras',
  'PyTorch',
  'Symfony',
  'ASP.NET Core',
  'Flutter',
  'Ember.js',
  'Next.js',
  'FastAPI',
  'Gatsby',
  'Ionic',
  'Svelte',
  'Nest.js',
  'SwiftUI',
  'React Native',
  'Quasar',
  'Tailwind CSS',
  'Django REST framework',
  'Flask RESTful',
  'Strapi',
] as const;
