version: '3.8'
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env.production
    environment:
      DB_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:${DB_PORT}/${POSTGRES_DB}?schema=public
    ports:
      - '3000:3000'
      - '8080:8080'
    depends_on:
      - database
    command: sh -c "yarn start:prod"

  database:
    image: postgres
    restart: always
    env_file:
      - .env.production
    ports:
      - '${DB_PORT}:${DB_PORT}'

  nginx:
    build:
      context: ./nginx
    restart: always
    ports:
      - '80:80'
    depends_on:
      - app
      - database
